// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD93aSL0-kHJGH9y4ooGR9Ywito51-6BmM',
    appId: '1:150878429110:web:6260088a8b9211d3386b17',
    messagingSenderId: '150878429110',
    projectId: 'healup-e4c79',
    authDomain: 'healup-e4c79.firebaseapp.com',
    storageBucket: 'healup-e4c79.firebasestorage.app',
    measurementId: 'G-64L6E1VK62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE8Np1v3GFvTH51cQvaRyWtJf8v226Keo',
    appId: '1:150878429110:android:7ba3d301afc40a42386b17',
    messagingSenderId: '150878429110',
    projectId: 'healup-e4c79',
    storageBucket: 'healup-e4c79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCed-bYww3Dwj5qbbyo2_SIXpaBPMhr4Zo',
    appId: '1:150878429110:ios:2aa41766ca1a14e7386b17',
    messagingSenderId: '150878429110',
    projectId: 'healup-e4c79',
    storageBucket: 'healup-e4c79.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );
}
